
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fk
  password: 12345678

development:
  <<: *default
  database: fk_development

  
test:
  <<: *default
  database: fk_test


production:
  <<: *default
  database: fk_production
  username: fk
  password: <%= ENV['FK_DATABASE_PASSWORD'] %>
